name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for contributing to the project, issues will help us provide a more polished tool'
        pr-message: 'Thanks for contributing to the project, your PR will be reviewed as soon as possible'
